/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const addTodo: typeof import('./src/api/todo.js')['addTodo']
  const getTodos: typeof import('./src/api/todo.js')['getTodos']
  const http: typeof import('./src/composables/http.js')['http']
  const updateTodo: typeof import('./src/api/todo.js')['updateTodo']
}
