/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const addTodo: typeof import('./src/api/todo.js')['addTodo']
  const createTodo: typeof import('./src/api/todo.js')['createTodo']
  const deleteTodo: typeof import('./src/api/todo.js')['deleteTodo']
  const fetchTodos: typeof import('./src/api/todo.js')['fetchTodos']
  const getTodoStats: typeof import('./src/api/todo.js')['getTodoStats']
  const getTodos: typeof import('./src/api/todo.js')['getTodos']
  const http: typeof import('./src/composables/http.js')['http']
  const login: typeof import('./src/api/auth.js')['login']
  const logout: typeof import('./src/api/auth.js')['logout']
  const register: typeof import('./src/api/auth.js')['register']
  const removeTodo: typeof import('./src/api/todo.js')['removeTodo']
  const updateTodo: typeof import('./src/api/todo.js')['updateTodo']
  const updateTodoPomodoros: typeof import('./src/api/todo.js')['updateTodoPomodoros']
  const useNetworkStatus: typeof import('./src/composables/useNetworkStatus.js')['useNetworkStatus']
}
